apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: servicex
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/configmap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
