apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authorizationpolicy-X.yaml
- configmap-X.yaml
- requestauthentication-X.yaml
- secret.yaml
- servicex-deploy.yaml
- virtualservice.yaml
